// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: data/emp_request.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age     int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Emp) Reset() {
	*x = Emp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_emp_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emp) ProtoMessage() {}

func (x *Emp) ProtoReflect() protoreflect.Message {
	mi := &file_data_emp_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emp.ProtoReflect.Descriptor instead.
func (*Emp) Descriptor() ([]byte, []int) {
	return file_data_emp_request_proto_rawDescGZIP(), []int{0}
}

func (x *Emp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Emp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emp) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Emp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EmpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileType string `protobuf:"bytes,1,opt,name=fileType,proto3" json:"fileType,omitempty"`
	Emp      *Emp   `protobuf:"bytes,2,opt,name=emp,proto3" json:"emp,omitempty"`
}

func (x *EmpReq) Reset() {
	*x = EmpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_emp_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpReq) ProtoMessage() {}

func (x *EmpReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_emp_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpReq.ProtoReflect.Descriptor instead.
func (*EmpReq) Descriptor() ([]byte, []int) {
	return file_data_emp_request_proto_rawDescGZIP(), []int{1}
}

func (x *EmpReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *EmpReq) GetEmp() *Emp {
	if x != nil {
		return x.Emp
	}
	return nil
}

type NoArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoArg) Reset() {
	*x = NoArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_emp_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoArg) ProtoMessage() {}

func (x *NoArg) ProtoReflect() protoreflect.Message {
	mi := &file_data_emp_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoArg.ProtoReflect.Descriptor instead.
func (*NoArg) Descriptor() ([]byte, []int) {
	return file_data_emp_request_proto_rawDescGZIP(), []int{2}
}

type EmpResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EmpResp) Reset() {
	*x = EmpResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_emp_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpResp) ProtoMessage() {}

func (x *EmpResp) ProtoReflect() protoreflect.Message {
	mi := &file_data_emp_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpResp.ProtoReflect.Descriptor instead.
func (*EmpResp) Descriptor() ([]byte, []int) {
	return file_data_emp_request_proto_rawDescGZIP(), []int{3}
}

func (x *EmpResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emp []*Emp `protobuf:"bytes,1,rep,name=emp,proto3" json:"emp,omitempty"`
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_emp_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_data_emp_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_data_emp_request_proto_rawDescGZIP(), []int{4}
}

func (x *GetResp) GetEmp() []*Emp {
	if x != nil {
		return x.Emp
	}
	return nil
}

var File_data_emp_request_proto protoreflect.FileDescriptor

var file_data_emp_request_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x65, 0x6d, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55,
	0x0a, 0x03, 0x45, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x06, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x65,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x45, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x6d, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x4e, 0x6f, 0x41, 0x72,
	0x67, 0x22, 0x19, 0x0a, 0x07, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x03, 0x65, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x52,
	0x03, 0x65, 0x6d, 0x70, 0x32, 0x87, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x23, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4e, 0x6f, 0x41, 0x72, 0x67, 0x1a, 0x0d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x04, 0x45, 0x64, 0x69, 0x74, 0x12,
	0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x73, 0x76, 0x63, 0x32, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_data_emp_request_proto_rawDescOnce sync.Once
	file_data_emp_request_proto_rawDescData = file_data_emp_request_proto_rawDesc
)

func file_data_emp_request_proto_rawDescGZIP() []byte {
	file_data_emp_request_proto_rawDescOnce.Do(func() {
		file_data_emp_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_emp_request_proto_rawDescData)
	})
	return file_data_emp_request_proto_rawDescData
}

var file_data_emp_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_data_emp_request_proto_goTypes = []interface{}{
	(*Emp)(nil),     // 0: data.Emp
	(*EmpReq)(nil),  // 1: data.EmpReq
	(*NoArg)(nil),   // 2: data.NoArg
	(*EmpResp)(nil), // 3: data.EmpResp
	(*GetResp)(nil), // 4: data.GetResp
}
var file_data_emp_request_proto_depIdxs = []int32{
	0, // 0: data.EmpReq.emp:type_name -> data.Emp
	0, // 1: data.GetResp.emp:type_name -> data.Emp
	1, // 2: data.CreateEmpService.Create:input_type -> data.EmpReq
	2, // 3: data.CreateEmpService.Get:input_type -> data.NoArg
	1, // 4: data.CreateEmpService.Edit:input_type -> data.EmpReq
	3, // 5: data.CreateEmpService.Create:output_type -> data.EmpResp
	4, // 6: data.CreateEmpService.Get:output_type -> data.GetResp
	3, // 7: data.CreateEmpService.Edit:output_type -> data.EmpResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_data_emp_request_proto_init() }
func file_data_emp_request_proto_init() {
	if File_data_emp_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_emp_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_emp_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_emp_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_emp_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_emp_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_emp_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_emp_request_proto_goTypes,
		DependencyIndexes: file_data_emp_request_proto_depIdxs,
		MessageInfos:      file_data_emp_request_proto_msgTypes,
	}.Build()
	File_data_emp_request_proto = out.File
	file_data_emp_request_proto_rawDesc = nil
	file_data_emp_request_proto_goTypes = nil
	file_data_emp_request_proto_depIdxs = nil
}
